name: onedaytrip
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


#----------------------- PACKAGES -------------------------#
dependencies:
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
#  firebase_core: ^3.1.1
#  firebase_messaging: ^15.0.2

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6


#  awesome_notifications: ^0.8.2
  flutter_local_notifications: ^13.0.0

  # State Management
  get: ^4.6.5
  #get_storage: ^2.1.1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  uni_links: ^0.5.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.2


  # Product Specific


#---------------------- ./ PACKAGES END -----------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true



#---------------------- LOCAL ASSETS -----------------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/users/
    - assets/images/on_boarding_images/
    - assets/images/login_images/
    - assets/images/signup_images/
    - assets/images/verify_email_images/
    - assets/images/animations/
    - assets/images/places/
    - assets/images/banner/
    - assets/icons/payment_methods/


#---------------------- LOCAL ASSETS -----------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

